recipe/meta.yaml
Should go in soonish since a security fix release
=> Update to the fresh release

recipe/meta.yaml
=> update to 6.20180913

recipe/meta.yaml
=> update to 6.20180926

recipe/meta.yaml
=> update to 7.20181105

.ci_support/linux_.yaml, recipe/meta.yaml
=> added back git req

recipe/build.sh, recipe/meta.yaml
=> use bash not sh

.ci_support/linux_.yaml, recipe/meta.yaml
=>  MNT: Re-rendered with conda-build 3.17.8, conda-smithy 3.2.14, and conda-forge-pinning 2019.03.14

recipe/0001-add-magicmime-add-wcwidth-resolver-to-lts-11.22.patch, recipe/meta.yaml
=> build with ghc 8.4.2, using lts-13.6 resolver

recipe/meta.yaml, recipe/run_test.sh
=> removed run_test.sh ; added datalad test; added curl as run dependency

.azure-pipelines/run_docker_build.sh, README.md, recipe/meta.yaml
=> update to 7.20190503

recipe/meta.yaml
=> updated to 7.20190507

recipe/LICENSE, recipe/meta.yaml
=> update to 7.20190708; added license info and description

recipe/0001-added-extra-deps-for-fdo-notify-and-magic.patch, recipe/build.sh, recipe/meta.yaml
=> update to 20190819.  add comments to recipe and build script.

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/run_docker_build.sh, .gitattributes, README.md, recipe/meta.yaml
=> update to 7.20190912

recipe/meta.yaml, recipe/post-link.sh
=> Is update to 7.20191024

.gitattributes, recipe/meta.yaml, recipe/post-link.sh
Checklist
* [ X Reset the build number to `0` (if the version changed)
=> update to 7.20191106

recipe/meta.yaml
=> update to 7.20191114

README.md, recipe/meta.yaml
=> update to 7.20191230

recipe/build.sh, recipe/meta.yaml
=> update to 7.20200202.7

recipe/meta.yaml
=> update to 7.20200204

recipe/meta.yaml
=> add ssh with connection caching

conda_build_config.yaml, recipe/meta.yaml
=> dropped git version req

recipe/meta.yaml
=> updated to 8.20200810

recipe/build_nodepFalse.sh, recipe/build_nodepTrue.sh, recipe/meta.yaml, recipe/post-link.sh
=> try enabling ghc/gcc compiler optimizations

.ci_support/linux_64_nodepFalse.yaml, .ci_support/linux_64_nodepTrue.yaml, recipe/build_nodepFalse.sh, recipe/meta.yaml
=> update to 8.20201103

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_nodepFalse.yaml, .ci_support/linux_64_nodepTrue.yaml, recipe/meta.yaml
=> update to 8.20201127 (standard build), 8.20201104 (standalone build)

.ci_support/linux_64_nodepFalse.yaml, .ci_support/linux_64_nodepTrue.yaml, .ci_support/migrations/libffi33.yaml, recipe/meta.yaml
=> Rebuild libffi33 0 1 hbd556f

recipe/meta.yaml
=> update to 8.20201129 (actually released on 2020-12-29)

.ci_support/linux_64_nodepFalse.yaml, .ci_support/linux_64_nodepTrue.yaml, .ci_support/migrations/libffi33.yaml, .scripts/run_docker_build.sh, recipe/meta.yaml
=> update to 8.20210127

.scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, LICENSE.txt, README.md, recipe/meta.yaml
=> update to 8.20210310

recipe/meta.yaml
=> update nodep to 8.20210224; update downstream datalad testing to 0.14.0

recipe/meta.yaml
=> update to 8.20210330

.scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, README.md, build-locally.py, recipe/meta.yaml
=> update to git-annex 8.20210428

.azure-pipelines/azure-pipelines-linux.yml, recipe/meta.yaml
=> update to 8.20210621

recipe/meta.yaml
=> update standalone version to 8.20210715; update downstream datalad to 0.14.7

.gitattributes, README.md, build-locally.py, recipe/meta.yaml
=> update gpg dependency

recipe/meta.yaml
=> updated to git-annex 8.20211123; added comments clarifying build process

recipe/meta.yaml
=> update to 8.20211231

recipe/meta.yaml
=> update to 10.20220127

README.md, recipe/build_nodepFalse.sh, recipe/meta.yaml
=> update to 10.20220322

README.md, recipe/meta.yaml
=> update to 10.20220504

recipe/meta.yaml
=> Is update to 10.20220525

.circleci/config.yml, .scripts/build_steps.sh, LICENSE.txt, build-locally.py, recipe/meta.yaml
=> update to 10.20220624

recipe/meta.yaml
=> updated to 10.20220724

recipe/meta.yaml
=> updated to 10.20220822

.ci_support/linux_64_nodepFalse.yaml, .ci_support/linux_64_nodepTrue.yaml, recipe/meta.yaml
=> update to 10.20220927

recipe/meta.yaml
=> provide new version 10.20230227 information

recipe/meta.yaml, recipe/update.sh
=> Update for new release (10.20230407) -- automating the update.

recipe/meta.yaml
=> Result of running recipe/update.sh - upgrade to 10.20230626
